= NPM CLI -  Commands and Flags

This cheat sheet covers the most common and helpful commands and flags for the npm CLI.

== Basic Usage

`-v, --version`:: Prints the current version of npm you are using
`<command> -h, --help`:: Quick help on the specified command
`-l`:: Displays full usage info

`npx [command]`:: Runs an arbitrary command from an npm module (either one installed locally, or fetched remotely)

== Create a new Node.js application

`npm init [--yes|-y|--scope]`:: Initializes a new Node.js project, creates a package.json file

[cols="25,75"]
|===
|`--yes, -y`
| Skips the init questionnaire

|`--scope`
| Creates a scoped application/module
|===

== Install Node Modules

`npm install <module_name>`:: Installs the specifed module as a dependency

[cols="25,75"]
|===
|`--save-dev`
| Installs the specifed module as a development dependecy

|`-g`
| Installs the module globally
|===

`npm install [--production]`:: Installs the modules specified in the package.json. The `--production` flag will not install development dependencies

`npm ci`:: Similar to `npm install`, but for use in automated environments such as test platforms, continuous integration, and deployment

`npm uninstall <module>`:: Removes a module

`npm outdated`:: Checks for outdated modules

`npm update`:: Updates modules to the latest version, respecting semver

`npm ls`:: Lists the installed modules

`npm prune`:: Removes any extraneous modules

`npm link`:: Symlinks a package folder

== NPM Scripts

`npm start`:: Runs a predefined command specified in the `start` property of a package's `scripts` object

`npm run [script]::` Runs a predefined command specified in the `[script]` property of package's `scripts` object

== Publish a Node Module

`npm whoami`:: Displays the npm username

`npm login`:: Login to the registry

`npm version [options]`:: Bumps the version of a module

[cols="25,75"]
|===
|`<newversion>`
| Bumps the version to the `<newversion>`.  ex: `npm version 1.1.0`

|`major`
| Bumps the major version by 1. ex: `npm version major` output: `v2.1.0`

|`minor`
| Bumps the minor verison by 1. ex: `npm version minor` output `v1.2.0`

|`patch`
| Bumps the patch version by 1. ex: `npm version patch` output: `v1.1.1`

|`premajor`
| Bumps the major version by 1, but as a prerelease. ex: `npm verison premajor` output: `v2.1.0-0`

|`preminor`
| Bumps the minor version by 1, but as a prerelease. ex: `npm verison preminor` output: `v1.2.0-0`

|`prepatch`
| Bumps the patch version by 1, but as a prerelease. ex: `npm verison prepatch` output: `v1.1.1-0`

|`prerelease`
| Bumps the prerelease version.  ex: `npm version prerelease` output: `1.1.0-1`

|`--preid=<prerelease-id>`
| Uses a custom prerelease id tag.  ex: `npm version prelease --preid=beta` example output: `1.1.0-beta.0`

|`from-git`
| Uses the latest git tag as the version
|===

`npm shrinkwrap`:: Locks down dependency versions for publication

`npm publish [--dry-run]`:: Publishs a module. Uses the `--dry-run` flag to get a preview of what will be published

`npm deprecate`:: Deprecates a version of a module

`npm unpublish`:: Removes a module from the registry

`npm dist-tag`:: Modifies package distribution tags

`npm logout`:: Logs out of the registry


== Misc

`npm audit`:: Runs a security audit

`npm bugs`:: Bugs for a module in a web browser

`npm docs`:: Docs for a module in a web browser

`npm fund`:: Retrieves funding information










